// packages/react/src/components/FeatureHub.tsx
import {
  type ClientContext,
  EdgeFeatureHubConfig,
  FeatureHub as fh,
  type FeatureHubConfig,
  fhLog,
  type ReadinessListenerHandle,
  Readyness,
} from "featurehub-javascript-client-sdk";
import { createContext, type FC, type ReactNode, useEffect, useMemo, useRef, useState } from "react";

export type UseFeatureHub = {
  readonly config: FeatureHubConfig;
  readonly client: ClientContext;
};

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
export const FeatureHubContext = createContext<UseFeatureHub>(undefined);
FeatureHubContext.displayName = "FeatureHub";

type Props = {
  /** The url to the running instance of the FeatureHub EDGE API */
  readonly url?: string;
  /** The FeatureHub API key -- can be found in the FeatureHub Admin Console */
  readonly apiKey?: string;
  /** Scopes FeatureHub context to userKey -- otherwise, context will be anonymous. */
  readonly userKey?: string;
  /** @deprecated use 'userKey` instead. */
  /** Use `userKey` prop instead. Scopes FeatureHub context to username -- otherwise, context will be anonymous. */
  readonly username?: string;
  /** Interval (in milliseconds) to poll FeatureHub for updates. [default: 60 seconds] */
  readonly pollInterval?: number;
  /** rest-active, rest-passive, streaming, defaults to rest-active */
  readonly connectionType?: string;
  /** wait until the repository becomes ready before rendering the children */
  readonly waitForReady?: boolean;
  /** The React application tree to inject the FeatureHub client into */
  readonly children: ReactNode;
};

/**
 * The FeatureHub React component. Use this as a top-level wrapper around your
 * main App component.
 *
 * @param {string} url - the url of the FeatureHub instance (required)
 * @param {string} apiKey - the apiKey key to use. Make sure it is the server-eval key! (required)
 * @param {string} userKey - the optional userKey to add user information to the FeatureHub context (optional)
 * @param {number} pollInterval - the desired polling interval (ms) to check for value updates (optional -- default 60 seconds)
 * @param {string} connectionType - rest-active, rest-passive, streaming, defaults to rest-active
 * @param {boolean} waitForReady - wait for readyness before rendering children
 * @param {JSX} children - the React component tree to inject FeatureHub into (required)
 *
 */
const FeatureHub: FC<Props> = ({
  url,
  apiKey,
  userKey,
  username,
  pollInterval = 60000,
  connectionType = "rest-active",
  waitForReady = true,
  children,
}: Props) => {
  const useSharedConfiguration = fh.isCompletelyConfigured();

  const {config, context} = useMemo(() => {
    if (useSharedConfiguration) {
      fhLog.log("FeatureHub React SDK: Using existing configuration.");
      return {config: fh.config, context: fh.context};
    }

    fhLog.log("FeatureHub React SDK: Creating config.");

    const config = EdgeFeatureHubConfig.config(url, apiKey);
    if (connectionType?.toLowerCase() === "rest-passive") {
      config.restPassive(pollInterval ?? 60000);
    } else if (connectionType?.toLowerCase() === "streaming") {
      config.streaming();
    } else {
      config.restActive(pollInterval ?? 60000);
    }

    return {config: config, context: config.context({userKey: userKey})};
  }, [url, apiKey, pollInterval, connectionType, userKey]);

  if (useSharedConfiguration) {
    context.userKey(userKey);
  }

  context.build();

  const [client] = useState(context);
  const [isReady, setIsReady] = useState(config.readiness === Readyness.Ready);
  const activeListenerIdRef = useRef<ReadinessListenerHandle | null>(null);

  useEffect(() => {
    const listener = async (readyness: Readyness) => {
      switch (readyness) {
        case Readyness.Failed:
          fhLog.error("FeatureHub React SDK: Connection failed!");
          break;
        case Readyness.NotReady:
          fhLog.log("FeatureHub React SDK: Connection not ready yet!");
          break;
        default: {
          // TODO: Remove deprecated username prop at some point since userKey keeps API language consistent
          const userInfo = username ?? userKey;

          if (!userInfo) {
            fhLog.log("FeatureHub React SDK: Connection ready! Using anonymous user context.");
            await client.build();
          } else {
            fhLog.log("FeatureHub React SDK: Connection ready! Using context with userKey set.");
            await client.userKey(userInfo).build(); // still the same userKey, doesn't change
          }

          setIsReady(true);
        }
      }
    };

    if (activeListenerIdRef.current !== null) {
      // Remove potential previous existing listener (for use-case when the username updates while component still mounted)
      config.removeReadinessListener(activeListenerIdRef.current);
    }

    const listenerId = config.addReadinessListener(listener, true);

    activeListenerIdRef.current = listenerId; // Keep track of registered listener

    return () => {
      fhLog.trace('FeatureHubSDK: shutting down effect of FeatureHub.');

      if (config) {
        // don't tell us any longer
        config.removeReadinessListener(listenerId);
      }

      if (!useSharedConfiguration && config) {
        fhLog.trace("FeatureHub React SDK: Terminating connection!");

        // should down the config only if we created it
        config.close();
      }
    };
  }, [userKey]);

  if (waitForReady && !isReady) {
    fhLog.trace("FeatureHub React SDK, not ready yet, returning empty div");
    return <div></div>;
  }

  return (
    <FeatureHubContext.Provider value={{ config: config, client }}>
      {children}
    </FeatureHubContext.Provider>
  );
};

export default FeatureHub;

// packages/solid/src/components/FeatureHub.tsx
import {
  type ClientContext,
  EdgeFeatureHubConfig,
  FeatureHub as fh,
  type FeatureHubConfig,
  fhLog,
  Readyness,
} from "featurehub-javascript-client-sdk";
import {
  type Accessor,
  type Component,
  createContext,
  createEffect,
  createMemo,
  createSignal,
  type JSX,
  on,
  onCleanup,
  Show,
} from "solid-js";

// Global ready signal — consumed by useFeature to know when to subscribe
export const [ready, setReady] = createSignal(false);

export type UseFeatureHub = {
  /** The FeatureHub config object */
  readonly config: Accessor<FeatureHubConfig>;
  /** The FeatureHub client context */
  readonly client: Accessor<ClientContext>;
};

export const FeatureHubContext = createContext<UseFeatureHub>(
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore
  null, // this will be assigned by the FeatureHub component
  {
    name: "FeatureHub",
  },
);

type Props = {
  /** The url to the running instance of the FeatureHub EDGE API */
  readonly url: string;
  /** The FeatureHub API key -- can be found in the FeatureHub Admin Console */
  readonly apiKey: string;
  /** Scopes FeatureHub context to userKey -- otherwise, context will be anonymous. */
  readonly userKey?: string;
  /** @deprecated Use `userKey` instead. */
  readonly username?: string;
  /** Interval (in milliseconds) to poll FeatureHub for updates. [default: 60 seconds] */
  readonly pollInterval?: number;
  /** Connection type (rest-active, rest-passive, streaming). Defaults to rest-active */
  readonly connectionType?: string;
  /** Wait until the repository becomes ready before rendering the children. [default: true] */
  readonly waitForReady?: boolean;
  /** The Solid application tree to inject the FeatureHub client into */
  readonly children: JSX.Element;
};

/**
 * The FeatureHub Solid component. Use this as a top-level wrapper around your
 * main App component.
 *
 * @param {string} url - the url of the FeatureHub instance (required)
 * @param {string} apiKey - the apiKey key to use. Make sure it is the server-eval key! (required)
 * @param {string} userKey - the userKey to add user information to the FeatureHub context (optional)
 * @param {number} pollInterval - the desired polling interval (ms) to check for value updates (optional -- default 60 seconds)
 * @param {string} connectionType - rest-active, rest-passive, streaming, defaults to rest-active
 * @param {boolean} waitForReady - wait for readiness before rendering children (default true)
 * @param {JSX} children - the Solid component tree to inject FeatureHub into (required)
 *
 */
export const FeatureHub: Component<Props> = (props): JSX.Element => {
  let listenerId: number | undefined;
  const useSharedConfiguration = fh.isCompletelyConfigured();
  const userKey = () => props.username ?? props.userKey ?? "";

  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore
  const [client, setClient] = createSignal<ClientContext>(null); // assigned in createMemo below
  const [readiness, setReadiness] = createSignal(Readyness.NotReady);

  /*
    SolidJS eagerly executes createMemo. We use it here to create (or reuse) the
    FeatureHub config once, register the readiness listener, and start the connection.
  */
  const config = createMemo<FeatureHubConfig>(() => {
    if (useSharedConfiguration) {
      fhLog.log("FeatureHub Solid SDK: Using existing config.");

      listenerId = fh.config.addReadinessListener(setReadiness, true);
      setClient(fh.context);
      fh.context.userKey(userKey()).build();

      return fh.config;
    }

    fhLog.log("FeatureHub Solid SDK: Creating config and context...");

    const cfg = EdgeFeatureHubConfig.config(props.url, props.apiKey);
    if (props.connectionType?.toLowerCase() === "rest-passive") {
      cfg.restPassive(props.pollInterval ?? 60000);
    } else if (props.connectionType?.toLowerCase() === "streaming") {
      cfg.streaming();
    } else {
      cfg.restActive(props.pollInterval ?? 60000);
    }

    listenerId = cfg.addReadinessListener(setReadiness, true);
    const context = cfg.newContext();
    setClient(context);

    context.userKey(userKey()).build();

    return cfg;
  });

  /*
    React to readiness state changes and userKey changes. When the connection
    becomes ready, build the context (with or without a user key).
  */
  createEffect(
    on([readiness, userKey], async () => {
      switch (readiness()) {
        case Readyness.Failed:
          if (!ready()) fhLog.error("FeatureHub Solid SDK: Connection failed!");
          break;
        case Readyness.NotReady:
          if (!ready()) fhLog.log("FeatureHub Solid SDK: Connection not ready yet!");
          break;
        default: {
          if (!userKey()) {
            fhLog.log("FeatureHub Solid SDK: Connection ready! Using anonymous user context.");
            await client().build();
            setReady(true);
            return;
          }

          fhLog.log("FeatureHub Solid SDK: Connection ready! Using context with userKey set.");
          setClient(await client().userKey(userKey()).build());
          setReady(true);
        }
      }
    }),
  );

  onCleanup(() => {
    fhLog.log("FeatureHub Solid SDK: Terminating connection!");
    if (listenerId) config().removeReadinessListener(listenerId);
    // Only shut down a config we created ourselves — don't touch shared configuration
    if (!useSharedConfiguration) {
      config().close();
    }
  });

  return (
    <FeatureHubContext.Provider value={{ config, client }}>
      <Show when={props.waitForReady === false || ready()} fallback={<></>}>
        {props.children}
      </Show>
    </FeatureHubContext.Provider>
  );
};
