// packages/solid/src/hooks/useFeature.tsx
import { type Accessor, createEffect, createSignal, on, onCleanup } from "solid-js";

import { useFeatureHub } from "./useFeatureHub";

/**
 * Convenience hook to subscribe to FeatureHub feature key.
 * NOTE: The key must be defined in your FeatureHub Admin Console.
 *
 * @param {string} key - the feature key
 * @returns {T | undefined} value - generic type of feature value (default boolean)
 */
export function useFeature<T = boolean>(key: string): Accessor<T | undefined> {
  const { client, ready } = useFeatureHub();

  let listenerId: number;
  const [value, setValue] = createSignal(client().feature(key).value);

  createEffect(
    on(ready, () => {
      // Being proper, we only subscribe to features when FeatureHub is ready
      if (!ready()) return;

      if (listenerId) {
        client().feature(key).removeListener(listenerId);
      }

      listenerId = client()
        .feature(key)
        .addListener(() => {
          setValue(client().feature(key).value);
        });

      // check if the feature exists already, which means the repository already has a value and
      // solid is asking for the effect AFTER the data has already arrived
      if (client().feature(key).isSet()) {
        setValue(() => client().feature(key).value);
      }
    }),
  );

  onCleanup(() => {
    client().feature(key).removeListener(listenerId);
  });

  return value as unknown as Accessor<T | undefined>;
}

// packages/react/src/hooks/useFeature.ts
import { type FeatureStateHolder } from "featurehub-javascript-client-sdk";
import { useEffect, useState } from "react";

import useFeatureHub from "./useFeatureHub";

/**
 * React hook to subscribe to FeatureHub feature key.
 * NOTE: The key must be defined in your FeatureHub Admin Console.
 *
 * @param {string} key - the feature key
 * @returns {FeatureValue} value - generic type of feature value (default boolean)
 */
function useFeature<T = boolean>(key: string): T | undefined {
  const featurehub = useFeatureHub();
  const [value, setValue] = useState(featurehub.client.feature(key).value);

  useEffect(() => {
    const listener = (fsh: FeatureStateHolder) => setValue(fsh.value);
    const feature = featurehub.client.feature(key);
    const listenerHandler = feature.addListener(listener);

    // if we already have a value when this request is made, trigger the listener otherwise we can use the
    // effect AFTER we have features and the client never uses them.
    if (feature.isSet()) {
      listener(feature);
    }

    return () => {
      featurehub.client.feature(key).removeListener(listenerHandler);
    };
  }, [featurehub, key]);

  return value as unknown as T | undefined;
}

export default useFeature;
